version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 3.19.0
  - dependency-name: url-loader
    versions:
    - 0.6.2
  - dependency-name: css-loader
    versions:
    - 0.28.11
  - dependency-name: file-loader
    versions:
    - 0.11.2
  - dependency-name: eslint-plugin-react
    versions:
    - 6.10.3
  - dependency-name: webpack
    versions:
    - 2.7.0
  - dependency-name: img-loader
    versions:
    - 2.0.1
